### ISSUE TITLE
DP83848 Support

### ISSUE THREAD

**Issue by Frenelius** [khoih-prog/Ethernet_Manager_STM32#1] opened 2021-07-05 12:09 UTC
Hello,

Do you know if PHY DP83848 is supported directly?

I am trying a generic STM32F407VET6 board with DP83848, using the configuration for LAN8720 but without success.

Everything compiles fine but it will not get an IP address nor respond to ping.

Thank you!

**Comment by khoih-prog** [comment] 2021-07-05 17:30
Thanks for your interest in the library.

**DP83848** is not currently supported, by this library as well as the underlying [EthernetWebServer_STM32 library](https://github.com/khoih-prog/EthernetWebServer_STM32).

What library are you using to have the simple Ethernet connection for **DP83848** and STM32F407VET6 ? How do you connect between STM32F407VET6 and **DP83848** ?

Can you turn on higher debug level to understand what wrong by changing [Ethernet_STM32_LAN8720 **defines.h** #L33-L35](https://github.com/khoih-prog/Ethernet_Manager_STM32/blob/main/examples/Ethernet_STM32_LAN8720/defines.h#L33-L35) to

```
// Debug Level from 0 to 4
#define _ETHERNET_WEBSERVER_LOGLEVEL_           4
#define _ETHERNET_MANAGER_STM32_LOGLEVEL_       4
```
and post the terminal output here ?

I'll definitely have a look, then order the **DP83848** to see if I can modify the library to add support to that **DP83848**. Certainly this current low-priority job will have higher priority when there are more feature requests.

**Comment by Frenelius** [comment] 2021-07-05 21:09
As of now I have been using STM32CubeIDE with Freertos and it works, but I would like to use the Arduino ecosystem, which I am more used to.

I have problems with the CubeIDE and Freertos stability and that is another reason why I would prefer to change.

Thank you!

**Comment by Frenelius** [comment] 2021-07-07 05:37
Hello again,

This is all I get in the serial monitor with the debug levels on 4:

07:36:52.567 -> [ETM] DHCP Failed
07:36:52.567 -> [ETHERNET_WEBSERVER] linkStatus =  LinkON
07:36:52.567 -> [ETM] begin:Ethernet not Connected
07:36:52.567 -> Ethernet not Connected! Please check.
07:36:52.567 -> Stop doubleResetDetecting
07:36:55.842 -> ClearFlag write = 0xd0d04321
07:36:55.842 -> [ETM] Start connectEthernet using DHCP
07:36:55.842 -> [ETM] MAC:FE-9D-F8-DB-DF-8A

07:37:56.795 -> [ETM] DHCP Failed
07:37:56.795 -> [ETHERNET_WEBSERVER] linkStatus =  LinkON
07:37:56.795 -> [ETHERNET_WEBSERVER] localEthernetIP =  0.0.0.0 , linkStatus =  LinkON
07:37:56.795 -> F
07:37:56.795 -> Your stored Credentials :
07:37:56.795 -> MQTT Server = blank
07:37:56.795 -> Port = blank
07:37:56.795 -> MQTT UserName = blank
07:37:56.795 -> MQTT PWD = blank
07:37:56.795 -> Subs Topics = blank
07:37:56.795 -> Pubs Topics = blank

I have used the "Ethernet_STM32_LAN8720" example.

**Comment by khoih-prog** [comment] 2021-07-10 02:53
The issue is in the core and/or the underlying [**STM32Ethernet** library](https://github.com/stm32duino/STM32Ethernet) as you can see in these following issues :

1. [**Generic PHY support** #34](https://github.com/stm32duino/STM32Ethernet/issues/34)
2. [**Support for DP83848_PHY ?** #15](https://github.com/stm32duino/STM32Ethernet/issues/15)

I'm closing the issue now and will reopen when DP83848 would have been already supported.

**Closed as completed by khoih-prog** 2021-07-10 02:53 UTC
